export const STATE_DISPLAY = {
  alabama: 'Alabama', alaska: 'Alaska', arizona: 'Arizona', arkansas: 'Arkansas',
  california: 'California', colorado: 'Colorado', connecticut: 'Connecticut',
  delaware: 'Delaware', florida: 'Florida', georgia: 'Georgia', hawaii: 'Hawaii',
  idaho: 'Idaho', illinois: 'Illinois', indiana: 'Indiana', iowa: 'Iowa',
  kansas: 'Kansas', kentucky: 'Kentucky', louisiana: 'Louisiana', maine: 'Maine',
  maryland: 'Maryland', massachusetts: 'Massachusetts', michigan: 'Michigan',
  minnesota: 'Minnesota', mississippi: 'Mississippi', missouri: 'Missouri',
  montana: 'Montana', nebraska: 'Nebraska', nevada: 'Nevada',
  'new-hampshire': 'New Hampshire', 'new-jersey': 'New Jersey',
  'new-mexico': 'New Mexico', 'new-york': 'New York',
  'north-carolina': 'North Carolina', 'north-dakota': 'North Dakota',
  ohio: 'Ohio', oklahoma: 'Oklahoma', oregon: 'Oregon', pennsylvania: 'Pennsylvania',
  'rhode-island': 'Rhode Island', 'south-carolina': 'South Carolina',
  'south-dakota': 'South Dakota', tennessee: 'Tennessee', texas: 'Texas',
  utah: 'Utah', vermont: 'Vermont', virginia: 'Virginia', washington: 'Washington',
  'west-virginia': 'West Virginia', wisconsin: 'Wisconsin', wyoming: 'Wyoming',
};

export const STATE_SLUGS = Object.keys(STATE_DISPLAY);

export const LANG_NAMES = {
  en: 'English', es: 'Spanish', zh: 'Chinese', ru: 'Russian', vi: 'Vietnamese',
  hy: 'Armenian', hi: 'Hindi', pa: 'Punjabi', ht: 'Haitian Creole', ko: 'Korean',
  ar: 'Arabic', fr: 'French', de: 'German', ua: 'Ukrainian', so: 'Somali',
  sw: 'Swahili', my: 'Burmese', ne: 'Nepali', pt: 'Portuguese', ja: 'Japanese',
  hmn: 'Hmong', tl: 'Tagalog', sm: 'Samoan', to: 'Tongan', haw: 'Hawaiian',
  mh: 'Marshallese', ilo: 'Ilocano', chk: 'Chuukese',
};

export const CATEGORY_LABELS = {
  car: 'Car (DMV)',
  cdl: 'CDL',
  motorcycle: 'Motorcycle',
};

// `dmvAbbr` is the short tag users actually see at their state's
// driver-licensing office. Most states are "DMV" colloquially; a
// few use a different acronym (WA: DOL, IL/MI: SOS, PA: PennDOT,
// etc.). Used in user-facing copy (button labels, FAQ) to match
// what the customer will encounter when they take their real test.
export const STATE_META = {
  alabama: { agency: 'Alabama Law Enforcement Agency (ALEA)', abbr: 'AL', dmvAbbr: 'DMV' },
  alaska: { agency: 'Alaska Division of Motor Vehicles', abbr: 'AK', dmvAbbr: 'DMV' },
  arizona: { agency: 'Arizona Motor Vehicle Division', abbr: 'AZ', dmvAbbr: 'MVD' },
  arkansas: { agency: 'Arkansas Department of Finance and Administration', abbr: 'AR', dmvAbbr: 'DMV' },
  california: { agency: 'California Department of Motor Vehicles', abbr: 'CA', dmvAbbr: 'DMV' },
  colorado: { agency: 'Colorado Division of Motor Vehicles', abbr: 'CO', dmvAbbr: 'DMV' },
  connecticut: { agency: 'Connecticut Department of Motor Vehicles', abbr: 'CT', dmvAbbr: 'DMV' },
  delaware: { agency: 'Delaware Division of Motor Vehicles', abbr: 'DE', dmvAbbr: 'DMV' },
  florida: { agency: 'Florida Department of Highway Safety and Motor Vehicles', abbr: 'FL', dmvAbbr: 'DMV' },
  georgia: { agency: 'Georgia Department of Driver Services', abbr: 'GA', dmvAbbr: 'DDS' },
  hawaii: { agency: 'Hawaii County of Finance', abbr: 'HI', dmvAbbr: 'DMV' },
  idaho: { agency: 'Idaho Transportation Department', abbr: 'ID', dmvAbbr: 'DMV' },
  illinois: { agency: 'Illinois Secretary of State', abbr: 'IL', dmvAbbr: 'SOS' },
  indiana: { agency: 'Indiana Bureau of Motor Vehicles', abbr: 'IN', dmvAbbr: 'BMV' },
  iowa: { agency: 'Iowa Department of Transportation', abbr: 'IA', dmvAbbr: 'DOT' },
  kansas: { agency: 'Kansas Division of Vehicles', abbr: 'KS', dmvAbbr: 'DMV' },
  kentucky: { agency: 'Kentucky Transportation Cabinet', abbr: 'KY', dmvAbbr: 'DMV' },
  louisiana: { agency: 'Louisiana Office of Motor Vehicles', abbr: 'LA', dmvAbbr: 'OMV' },
  maine: { agency: 'Maine Bureau of Motor Vehicles', abbr: 'ME', dmvAbbr: 'BMV' },
  maryland: { agency: 'Maryland Motor Vehicle Administration', abbr: 'MD', dmvAbbr: 'MVA' },
  massachusetts: { agency: 'Massachusetts Registry of Motor Vehicles', abbr: 'MA', dmvAbbr: 'RMV' },
  michigan: { agency: 'Michigan Secretary of State', abbr: 'MI', dmvAbbr: 'SOS' },
  minnesota: { agency: 'Minnesota Department of Public Safety', abbr: 'MN', dmvAbbr: 'DVS' },
  mississippi: { agency: 'Mississippi Department of Public Safety', abbr: 'MS', dmvAbbr: 'DMV' },
  missouri: { agency: 'Missouri Department of Revenue', abbr: 'MO', dmvAbbr: 'DMV' },
  montana: { agency: 'Montana Motor Vehicle Division', abbr: 'MT', dmvAbbr: 'MVD' },
  nebraska: { agency: 'Nebraska Department of Motor Vehicles', abbr: 'NE', dmvAbbr: 'DMV' },
  nevada: { agency: 'Nevada Department of Motor Vehicles', abbr: 'NV', dmvAbbr: 'DMV' },
  'new-hampshire': { agency: 'New Hampshire Division of Motor Vehicles', abbr: 'NH', dmvAbbr: 'DMV' },
  'new-jersey': { agency: 'New Jersey Motor Vehicle Commission', abbr: 'NJ', dmvAbbr: 'MVC' },
  'new-mexico': { agency: 'New Mexico Motor Vehicle Division', abbr: 'NM', dmvAbbr: 'MVD' },
  'new-york': { agency: 'New York Department of Motor Vehicles', abbr: 'NY', dmvAbbr: 'DMV' },
  'north-carolina': { agency: 'North Carolina Division of Motor Vehicles', abbr: 'NC', dmvAbbr: 'DMV' },
  'north-dakota': { agency: 'North Dakota Department of Transportation', abbr: 'ND', dmvAbbr: 'DOT' },
  ohio: { agency: 'Ohio Bureau of Motor Vehicles', abbr: 'OH', dmvAbbr: 'BMV' },
  oklahoma: { agency: 'Oklahoma Department of Public Safety', abbr: 'OK', dmvAbbr: 'DPS' },
  oregon: { agency: 'Oregon Driver and Motor Vehicle Services', abbr: 'OR', dmvAbbr: 'DMV' },
  pennsylvania: { agency: 'Pennsylvania Department of Transportation', abbr: 'PA', dmvAbbr: 'PennDOT' },
  'rhode-island': { agency: 'Rhode Island Division of Motor Vehicles', abbr: 'RI', dmvAbbr: 'DMV' },
  'south-carolina': { agency: 'South Carolina Department of Motor Vehicles', abbr: 'SC', dmvAbbr: 'DMV' },
  'south-dakota': { agency: 'South Dakota Department of Public Safety', abbr: 'SD', dmvAbbr: 'DPS' },
  tennessee: { agency: 'Tennessee Department of Safety and Homeland Security', abbr: 'TN', dmvAbbr: 'DOS' },
  texas: { agency: 'Texas Department of Public Safety', abbr: 'TX', dmvAbbr: 'DPS' },
  utah: { agency: 'Utah Driver License Division', abbr: 'UT', dmvAbbr: 'DLD' },
  vermont: { agency: 'Vermont Department of Motor Vehicles', abbr: 'VT', dmvAbbr: 'DMV' },
  virginia: { agency: 'Virginia Department of Motor Vehicles', abbr: 'VA', dmvAbbr: 'DMV' },
  washington: { agency: 'Washington Department of Licensing', abbr: 'WA', dmvAbbr: 'DOL' },
  'west-virginia': { agency: 'West Virginia Division of Motor Vehicles', abbr: 'WV', dmvAbbr: 'DMV' },
  wisconsin: { agency: 'Wisconsin Division of Motor Vehicles', abbr: 'WI', dmvAbbr: 'DMV' },
  wyoming: { agency: 'Wyoming Department of Transportation', abbr: 'WY', dmvAbbr: 'DOT' },
};
