export const STATE_DISPLAY = {
  alabama: 'Alabama', alaska: 'Alaska', arizona: 'Arizona', arkansas: 'Arkansas',
  california: 'California', colorado: 'Colorado', connecticut: 'Connecticut',
  delaware: 'Delaware', florida: 'Florida', georgia: 'Georgia', hawaii: 'Hawaii',
  idaho: 'Idaho', illinois: 'Illinois', indiana: 'Indiana', iowa: 'Iowa',
  kansas: 'Kansas', kentucky: 'Kentucky', louisiana: 'Louisiana', maine: 'Maine',
  maryland: 'Maryland', massachusetts: 'Massachusetts', michigan: 'Michigan',
  minnesota: 'Minnesota', mississippi: 'Mississippi', missouri: 'Missouri',
  montana: 'Montana', nebraska: 'Nebraska', nevada: 'Nevada',
  'new-hampshire': 'New Hampshire', 'new-jersey': 'New Jersey',
  'new-mexico': 'New Mexico', 'new-york': 'New York',
  'north-carolina': 'North Carolina', 'north-dakota': 'North Dakota',
  ohio: 'Ohio', oklahoma: 'Oklahoma', oregon: 'Oregon', pennsylvania: 'Pennsylvania',
  'rhode-island': 'Rhode Island', 'south-carolina': 'South Carolina',
  'south-dakota': 'South Dakota', tennessee: 'Tennessee', texas: 'Texas',
  utah: 'Utah', vermont: 'Vermont', virginia: 'Virginia', washington: 'Washington',
  'west-virginia': 'West Virginia', wisconsin: 'Wisconsin', wyoming: 'Wyoming',
};

export const STATE_SLUGS = Object.keys(STATE_DISPLAY);

export const LANG_NAMES = {
  en: 'English', es: 'Spanish', zh: 'Chinese', ru: 'Russian', vi: 'Vietnamese',
  hy: 'Armenian', hi: 'Hindi', pa: 'Punjabi', ht: 'Haitian Creole', ko: 'Korean',
  ar: 'Arabic', fr: 'French', de: 'German', ua: 'Ukrainian', so: 'Somali',
  sw: 'Swahili', my: 'Burmese', ne: 'Nepali', pt: 'Portuguese', ja: 'Japanese',
  hmn: 'Hmong',
};

export const CATEGORY_LABELS = {
  car: 'Car (DMV)',
  cdl: 'CDL',
  motorcycle: 'Motorcycle',
};

export const STATE_META = {
  alabama: { agency: 'Alabama Law Enforcement Agency (ALEA)', abbr: 'AL' },
  alaska: { agency: 'Alaska Division of Motor Vehicles', abbr: 'AK' },
  arizona: { agency: 'Arizona Motor Vehicle Division', abbr: 'AZ' },
  arkansas: { agency: 'Arkansas Department of Finance and Administration', abbr: 'AR' },
  california: { agency: 'California Department of Motor Vehicles', abbr: 'CA' },
  colorado: { agency: 'Colorado Division of Motor Vehicles', abbr: 'CO' },
  connecticut: { agency: 'Connecticut Department of Motor Vehicles', abbr: 'CT' },
  delaware: { agency: 'Delaware Division of Motor Vehicles', abbr: 'DE' },
  florida: { agency: 'Florida Department of Highway Safety and Motor Vehicles', abbr: 'FL' },
  georgia: { agency: 'Georgia Department of Driver Services', abbr: 'GA' },
  hawaii: { agency: 'Hawaii County of Finance', abbr: 'HI' },
  idaho: { agency: 'Idaho Transportation Department', abbr: 'ID' },
  illinois: { agency: 'Illinois Secretary of State', abbr: 'IL' },
  indiana: { agency: 'Indiana Bureau of Motor Vehicles', abbr: 'IN' },
  iowa: { agency: 'Iowa Department of Transportation', abbr: 'IA' },
  kansas: { agency: 'Kansas Division of Vehicles', abbr: 'KS' },
  kentucky: { agency: 'Kentucky Transportation Cabinet', abbr: 'KY' },
  louisiana: { agency: 'Louisiana Office of Motor Vehicles', abbr: 'LA' },
  maine: { agency: 'Maine Bureau of Motor Vehicles', abbr: 'ME' },
  maryland: { agency: 'Maryland Motor Vehicle Administration', abbr: 'MD' },
  massachusetts: { agency: 'Massachusetts Registry of Motor Vehicles', abbr: 'MA' },
  michigan: { agency: 'Michigan Secretary of State', abbr: 'MI' },
  minnesota: { agency: 'Minnesota Department of Public Safety', abbr: 'MN' },
  mississippi: { agency: 'Mississippi Department of Public Safety', abbr: 'MS' },
  missouri: { agency: 'Missouri Department of Revenue', abbr: 'MO' },
  montana: { agency: 'Montana Motor Vehicle Division', abbr: 'MT' },
  nebraska: { agency: 'Nebraska Department of Motor Vehicles', abbr: 'NE' },
  nevada: { agency: 'Nevada Department of Motor Vehicles', abbr: 'NV' },
  'new-hampshire': { agency: 'New Hampshire Division of Motor Vehicles', abbr: 'NH' },
  'new-jersey': { agency: 'New Jersey Motor Vehicle Commission', abbr: 'NJ' },
  'new-mexico': { agency: 'New Mexico Motor Vehicle Division', abbr: 'NM' },
  'new-york': { agency: 'New York Department of Motor Vehicles', abbr: 'NY' },
  'north-carolina': { agency: 'North Carolina Division of Motor Vehicles', abbr: 'NC' },
  'north-dakota': { agency: 'North Dakota Department of Transportation', abbr: 'ND' },
  ohio: { agency: 'Ohio Bureau of Motor Vehicles', abbr: 'OH' },
  oklahoma: { agency: 'Oklahoma Department of Public Safety', abbr: 'OK' },
  oregon: { agency: 'Oregon Driver and Motor Vehicle Services', abbr: 'OR' },
  pennsylvania: { agency: 'Pennsylvania Department of Transportation', abbr: 'PA' },
  'rhode-island': { agency: 'Rhode Island Division of Motor Vehicles', abbr: 'RI' },
  'south-carolina': { agency: 'South Carolina Department of Motor Vehicles', abbr: 'SC' },
  'south-dakota': { agency: 'South Dakota Department of Public Safety', abbr: 'SD' },
  tennessee: { agency: 'Tennessee Department of Safety and Homeland Security', abbr: 'TN' },
  texas: { agency: 'Texas Department of Public Safety', abbr: 'TX' },
  utah: { agency: 'Utah Driver License Division', abbr: 'UT' },
  vermont: { agency: 'Vermont Department of Motor Vehicles', abbr: 'VT' },
  virginia: { agency: 'Virginia Department of Motor Vehicles', abbr: 'VA' },
  washington: { agency: 'Washington Department of Licensing', abbr: 'WA' },
  'west-virginia': { agency: 'West Virginia Division of Motor Vehicles', abbr: 'WV' },
  wisconsin: { agency: 'Wisconsin Division of Motor Vehicles', abbr: 'WI' },
  wyoming: { agency: 'Wyoming Department of Transportation', abbr: 'WY' },
};
